name: Deploy to EC2

on:
  push:
    branches:
      - main
      - beta

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code (for reference, not deployment)
        uses: actions/checkout@v4

      # SSH into EC2 and run deployment commands
      - name: SSH into EC2 & Deploy Laravel
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Choose the right path based on branch
            if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
              APP_PATH="/var/www/inventory/production/backend"
              BRANCH="main"
            else
              APP_PATH="/var/www/inventory/beta/backend"
              BRANCH="beta"
            fi

            echo "Deploying branch: $BRANCH to $APP_PATH"

            cd $APP_PATH

            # Ensure the repo is clean and up to date
            git fetch origin $BRANCH
            git reset --hard origin/$BRANCH

            # Install dependencies without touching .env
            composer install --no-interaction --prefer-dist --optimize-autoloader

            # Laravel optimizations
            php artisan optimize:clear
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan queue:restart

            echo "Backend deployed successfully for branch: $BRANCH"
