name: Deploy Laravel to EC2

on:
  push:
    branches:
      - main
      - beta

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: SSH & Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Determine deployment path based on branch
            if [ "${GITHUB_REF}" = "refs/heads/main" ]; then
              APP_DIR="/var/www/inventory/production/backend"
            else
              APP_DIR="/var/www/inventory/beta/backend"
            fi

            echo "Deploying branch ${GITHUB_REF##*/} to $APP_DIR"
            cd "$APP_DIR" || { echo "Directory $APP_DIR does not exist"; exit 1; }

            # Ensure git repo exists
            if [ ! -d ".git" ]; then
              echo "No git repo found in $APP_DIR. Please clone manually first."
              exit 1
            fi

            # Fetch and reset branch safely
            BRANCH=${GITHUB_REF##*/}
            git fetch origin "$BRANCH"
            git reset --hard "origin/$BRANCH"

            # Install PHP dependencies
            composer install --no-interaction --prefer-dist --optimize-autoloader

            # Laravel optimizations
            php artisan optimize:clear
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            # Restart queue workers
            php artisan queue:restart

            echo "Laravel backend deployed successfully for branch $BRANCH"
