name: Deploy Laravel to EC2

on:
  push:
    branches:
      - main
      - beta

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: SSH & Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Pick deployment path based on branch
            if [ "${GITHUB_REF}" = "refs/heads/main" ]; then
              APP_DIR="/var/www/inventory/production/backend"
            else
              APP_DIR="/var/www/inventory/beta/backend"
            fi

            cd "$APP_DIR" || exit 1

            # First-time setup check
            if [ ! -d ".git" ]; then
              echo "No git repo found in $APP_DIR. Please clone manually first."
              exit 1
            fi

            # Pull latest changes
            git fetch --all
            git reset --hard origin/${GITHUB_REF##*/}
            git pull origin ${GITHUB_REF##*/}

            # Install PHP dependencies
            composer install --no-interaction --prefer-dist --optimize-autoloader

            # Laravel optimizations
            php artisan optimize:clear
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            # Restart queue workers
            php artisan queue:restart

            echo "Laravel backend deployed for branch ${GITHUB_REF##*/}"
