name: Release on Tag Push

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          prerelease: ${{ contains(github.ref_name, 'beta') }}

      - name: Deploy to Staging (for beta)
        if: contains(github.ref_name, 'beta')
        run: echo "Deploying to staging server..."

      - name: Deploy to Production (for main)
        if: ${{ !contains(github.ref_name, 'beta') }}
        run: echo "Deploying to production server..."
